Update ict baseline pages
GSA/Section508.gov pull request #579
Opened 2023-08-31 15:16 UTC by alexwilsongsa

2023-09-20 15:43 UTC, kengdoj commented on _pages/acquisition/2018-05-29-buy.md
> +    The ICT Testing Baseline helps ensure that web content is accessible to people with disabilities and meets the legal obligations of Section 508. The ICT Testing Baseline describes how to evaluate
```suggestion
    The ICT Testing Baseline for Web helps ensure that web content is accessible to people with disabilities and meets the technical requirements of Section 508. The ICT Testing Baseline describes how to evaluate conformance to <a href="https://www.access-board.gov/ict/">the Revised 508 Standards</a>, which incorporate by reference the Web Content Accessibility Guidelines (WCAG) 2.0 Level A and AA Success Criteria. The Baseline for Web is organized by categories to help you easily identify applicable requirements. Note that the Baseline is not a test process and does not include testing tools; rather, it should be used to create an accessibility test process or validate an existing test process for completeness.
```

2023-09-20 16:13 UTC, kengdoj commented on _pages/test/2018-05-22-test-web-software.md
> +The ICT Testing Baseline describes how to evaluate conformance to [the Revised 508 Standards][21], which align with WCAG 2.0 Level A and AA Success Criteria. It is organized by categories to help you
```suggestion
The ICT Testing Baseline describes what to evaluate for conformance to [the Revised 508 Standards][21], which align with WCAG 2.0 Level A and AA Success Criteria. It is organized by categories to help you easily identify applicable requirements. Note that the Baseline is not a test process and does not include testing tools; rather, it should be used to ***create*** an accessibility test process or validate an existing test process for completeness.
```

2023-09-20 16:14 UTC, kengdoj requested changes
A few suggested edits. Thanks!

2023-09-22 16:55 UTC, drewnielson commented
> A few suggested edits. Thanks!

Thanks @kengdoj. Suggested changes incorporated, and added USAB as contributor.

2023-09-22 16:58 UTC, drewnielson approved these changes

2023-09-22 17:15 UTC, merged